import hashlib
import math
from threading import Lock
from typing import Iterator

from src.custom_logger import CrawlLogger

'''
A Bloom Filter is a probabilistic Data Structure used in place of a Hash Set to test
weather an element is a member of a set. Unlike a Hash Set, a Bloom Filter can return 
false positives but never false negatives. This works in our case as we have to crawl 
100s of 1000s of pages and we want to avoid re-crawling the same page, it is okay if we 
miss a few pages as long as we don't crawl the same page multiple times.

Bloom Filter Workings:
1. Size
    Given n = number of items expected to be stored in the filter
    p = false positive probability in decimal
    The standard formula for calculating the size of the bit array (m) and the number of hash functions (k) is as follows:
    no of bits (m) = -n * ln(p) / (ln(2)^2)
    no of hash functions (k) = (m/n) * ln(2)

2. Hash Functions
    _positions() method generates k different hash values for the given item using SHA-256 hash function.
    We generate the bit positions for k hash functions by prefixing the item with the index of the hash 
    function and then hashing it.
    
3. Setting and Unsetting Bits
    The add() method sets the bits at the positions generated by the hash functions to 1
    To get the byte index = position // 8
    To get the bit index = position % 8
    To set the bit at the position, we use the bitwise OR operation with a mask that has a 1 at the bit index.

'''
class BloomFilter:
    def __init__(
        self,
        logger: CrawlLogger,
        expected_items: int = 100_000,
        false_positive_rate: float = 0.001,
    ):
        expected_items = max(1, expected_items)
        false_positive_rate = max(0.000001, min(0.999999, false_positive_rate))
        self.logger = logger

        self.capacity = expected_items
        self.false_positive_rate = false_positive_rate
        self.num_bits = math.ceil(
            -expected_items * math.log(false_positive_rate) / math.log(2) ** 2
        )
        self.num_hashes = max(
            1, round(self.num_bits / expected_items * math.log(2))
        )
        self.bits = bytearray((self.num_bits + 7) // 8)
        self.lock = Lock()
        self._insertions = 0
        self.overflow_logged = False

    def _positions(self, item: str) -> Iterator[int]:
        data = item.encode("utf-8")
        for index in range(self.num_hashes):
            prefix = index.to_bytes(4, byteorder="big")
            digest = hashlib.sha256(prefix + data).digest()
            yield int.from_bytes(digest, byteorder="big") % self.num_bits

    def add(self, item: str) -> None:
        positions = tuple(self._positions(item))
        with self.lock:
            if all(self.bits[p // 8] & (1 << (p % 8)) for p in positions):
                return
            if self._insertions >= self.capacity:
                if not self.overflow_logged:
                    self.overflow_logged = True
                    self.logger.event("bloom_filter_overflow", level='WARNING', expected_items=self.capacity,
                                 log="BloomFilter capacity reached; use a larger expected_items value before starting the crawl")
            for position in positions:
                self.bits[position // 8] |= 1 << (position % 8)
            self._insertions += 1

    def __contains__(self, item: str) -> bool:
        positions = tuple(self._positions(item))
        with self.lock:
            return all(
                self.bits[p // 8] & (1 << (p % 8))
                for p in positions
            )
